# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_and_test:
    working_directory: /go/src/github.com/aerogear/aerogear-app-metrics

    docker:
      - image: circleci/golang:1.9
      - image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
        ports:
          - 5432:5432
        environment:
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_USER: postgresql
          POSTGRESQL_DATABASE: aerogear_mobile_metrics
    
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make build
      - run: make test-integration-cover
      - run: /go/bin/goveralls -coverprofile=coverage-all.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

  docker_release:
    working_directory: /go/src/github.com/aerogear/aerogear-app-metrics
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: go get github.com/goreleaser/goreleaser
      - checkout
      - run: make release
      - run: make docker_build_release
      - run: make docker_push_release
      - store_artifacts:
        path: dist

workflows:
  version: 2
  build_and_docker_push:
    jobs:
      - build_and_test
      - docker_release:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
